artifact_location: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/0
creation_time: 1748001749242
experiment_id: '0'
last_update_time: 1748001749242
lifecycle_stage: active
name: Default
