aliases: []
creation_timestamp: 1748002129859
current_stage: None
description: null
last_updated_timestamp: 1748002129859
name: DecisionTree-AdultIncome-Model
run_id: 887d84bd666d40cda658a9f62ff637a0
run_link: null
source: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/479965316876761057/887d84bd666d40cda658a9f62ff637a0/artifacts/model
status: READY
status_message: null
storage_location: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/479965316876761057/887d84bd666d40cda658a9f62ff637a0/artifacts/model
user_id: null
version: 2
