aliases: []
creation_timestamp: 1748001751857
current_stage: Archived
description: null
last_updated_timestamp: 1748002129864
name: LogisticRegression-AdultIncome-Model
run_id: fe87aac7f9df4998b507054ff422ad97
run_link: null
source: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/479965316876761057/fe87aac7f9df4998b507054ff422ad97/artifacts/model
status: READY
status_message: null
storage_location: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/479965316876761057/fe87aac7f9df4998b507054ff422ad97/artifacts/model
user_id: null
version: 1
