artifact_location: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/479965316876761057
creation_time: 1748001749248
experiment_id: '479965316876761057'
last_update_time: 1748001749248
lifecycle_stage: active
name: adult-income-workshop
