artifact_uri: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/479965316876761057/86f0ddf4eccf4f1bba1060389daebadb/artifacts
end_time: 1748002128289
entry_point_name: ''
experiment_id: '479965316876761057'
lifecycle_stage: active
run_id: 86f0ddf4eccf4f1bba1060389daebadb
run_name: logistic-regression
run_uuid: 86f0ddf4eccf4f1bba1060389daebadb
source_name: ''
source_type: 4
source_version: ''
start_time: 1748002126274
status: 3
tags: []
user_id: rkargul
