artifact_uri: /Users/rkargul/Documents/work/JNations-2025/mlflow-tracking-production-f89b.up.railway.app/479965316876761057/0b0d0242fbb44ae1bf50fccf21f61fe3/artifacts
end_time: 1748001753305
entry_point_name: ''
experiment_id: '479965316876761057'
lifecycle_stage: active
run_id: 0b0d0242fbb44ae1bf50fccf21f61fe3
run_name: decision-tree
run_uuid: 0b0d0242fbb44ae1bf50fccf21f61fe3
source_name: ''
source_type: 4
source_version: ''
start_time: 1748001751862
status: 3
tags: []
user_id: rkargul
